//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AghDataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<CorporateClient> CorporateClients { get; set; }
        public virtual DbSet<IndividualClient> IndividualClients { get; set; }
        public virtual DbSet<CorporateClientEmploye> CorporateClientEmployes { get; set; }
        public virtual DbSet<Workshop> Workshops { get; set; }
        public virtual DbSet<WorkshopPrice> WorkshopPrices { get; set; }
        public virtual DbSet<Conference> Conferences { get; set; }
        public virtual DbSet<ConferencePrices> ConferencePrices { get; set; }
        public virtual DbSet<Student> Students1 { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Street> Streets { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Building> Buildings { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
    }
}
